HOME = "/"
CONTACT = "/contact"
PROFILE = "/profile"
PROJECTS = "/projects"

GITHUB = "https://github.com/maufranzar"
GITHUB_NN = "https://github.com/maufranzar/NN"
GITHUB_IOT = "https://github.com/maufranzar/esp32"
TWITTER = "https://x.com/maufranzar"
SPOTIFY = "https://open.spotify.com/user/bmbpwp9beicgbbbaq0rmjwawm"
INSTAGRAM = "https://www.instagram.com/maufranzar/"
LINKEDIN = "https://pe.linkedin.com/in/maufranzar"

PLAT_LINUX = "https://platzi.com/p/maufranzar/ruta/8350-cloud-servidores/diploma/detalle/"
PLAT_DATOS = "https://platzi.com/p/maufranzar/ruta/13482-analisis-datos-python/diploma/detalle/"
PLAT_ML = "https://platzi.com/p/maufranzar/ruta/13488-datos-ml/diploma/detalle/"
PLAT_IA = "https://platzi.com/p/maufranzar/ruta/13490-datos-fundamentos-tecnicos/diploma/detalle/"
