HOME = "/"
CONTACT = "/contact"
PROFILE = "/profile"
PROJECTS = "/projects"

GITHUB = "https://github.com/maufranzar"
TWITTER = "https://x.com/maufranzar"
SPOTIFY = "https://open.spotify.com/user/bmbpwp9beicgbbbaq0rmjwawm"
INSTAGRAM = "https://www.instagram.com/maufranzar/"
LINKEDIN = "https://pe.linkedin.com/in/maufranzar"